config/routes.rb
Rails.application.routes.draw do
  devise_for :hotels, path: 'hotels', controllers: { sessions: "hotels/sessions", confirmations: "hotels/confirmations", registrations: "hotels/registrations", passwords: "hotels/passwords", mailer: "hotels/mailer"}
  devise_for :users, path: 'users'
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/background.png);">
  <div class="container">
    <h1>Guest ID</h1>
    <p>Registre-se uma vez, faça check-in em qualquer hotel</p>
    <%= link_to 'Sou um hospede', new_user_registration_path, class: 'btn btn-flat' %>
    <%= link_to 'Sou/trabalho em um Hotel', new_hotel_registration_path, class: 'btn btn-flat' %>
  </div>
</div>

<div class="container">
  <div class="card">
    <h3>O que é uma FNRH(Ficha Nacional de Registro de Hospedes)?</h3>
    <p>É um documento obrigatório de registro de hospedes que contém informações pessoais e relevantes a hospedagem.</p>
    <p>Essa ficha é transmitida diariamente para o Ministério do Turismo e Policia Federal pelo sistema do Hotel</p>
  </div>

    <div class="card">
    <h3>O Que é o Guest ID?</h3>
    <p>É uma FNRH(Ficha Nacional de Registro de Hospedes) digital</p>
  </div>

  <div class="card">
    <h3>Como funciona o Guest ID?</h3>
    <p>Você registra suas informações pessoais uma única vez e já está pronto para criar uma nova FNRH</p>
    <p>O compartilhamento da sua FNRH pode ser feito com hoteis cadastrados, ou via token para hoteis não cadastrados</p>
  </div>
</div>